dataset: 
  train:
    name: nyu_v2
    prob_ls: [0.9, 0.1]
    filenames: data_split/nyu/labeled/filename_list_train.txt
    dir: nyuv2/nyu_labeled_extracted.tar
    disp_name: nyu_v2_train
    eigen_valid_mask: true
    resize_to_hw:
      - 480
      - 640